[platformio]
default_envs = esp32dev

[env]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
build_unflags = -std=gnu++11

[env:esp32dev]

[env:esp32dev_four_channel]
build_flags =
    ${env.build_flags}
    -DMOTOR_OUTPUT_CHANNEL_COUNT=4
