[platformio]
default_envs = nodemcuv2

[env]
platform = platformio/espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
build_unflags = -std=gnu++11

[env:nodemcuv2]

[env:motor_test]
extends = env:nodemcuv2
build_flags =
    ${env.build_flags}
    -DMOTOR_TEST_ENABLED=1
    -DHARDWARE_CONFIGURATION_CONFIRMED=1
